/**
 * The sources this deployment serves, one docs page each. Must agree with the
 * Worker's `SOURCE_CONFIG` (packages/api/wrangler.toml); `tests/sources.test.ts`
 * checks that.
 */
export interface SourceDoc {
  /** Path segment in `/v1/{source}/…` and `/sources/{source}/`. */
  name: string;
  title: string;
  upstreamUrl: string;
  /** Plain prose: what the upstream is, what a record is, why its history matters. */
  summary: string;
  /** Payload fields that identify the real-world entity behind a key (tells reuse from resurrection). */
  entityFields: readonly string[];
  /** Whole archive readable by every tier — true only for sample data. */
  openArchive: boolean;
  /** Days a record stays in the upstream's own window before it drops out, if the upstream has one. */
  windowDays: number | null;
  sample: {
    key: string;
    /** A date with a stored capture, inside the archive. */
    date: string;
    from: string;
    to: string;
    /** One sentence on what the sample shows. */
    note: string;
  };
}

export const SOURCES: readonly SourceDoc[] = [
  {
    name: 'fixture_registry',
    title: 'Fixture registry (synthetic sample)',
    upstreamUrl: 'https://fixture.invalid/registry',
    summary:
      'A deterministic synthetic registry generated by @archive-api/fixture in the exact on-disk ' +
      'layout the capture harness emits: 400 records, 120 daily captures from 2025-01-01, a 365-day ' +
      'publisher window, and seven deliberately awkward cases (records that vanish and return, keys ' +
      'reused for different entities, a field that changes without changing the hash, a missing day, ' +
      'a truncated day). It exists so every endpoint can be tried without a key and so the pathological ' +
      'answers can be checked against a manifest.',
    entityFields: ['entity'],
    openArchive: true,
    windowDays: 365,
    sample: {
      // `cases.resurrect` in the fixture manifest: present, gone from day 40, back on day 70 changed.
      key: '2025-01-01|R000000',
      date: '2025-02-01',
      from: '2025-02-01',
      to: '2025-03-15',
      note: 'Record R000000 disappears on 2025-02-10 and returns on 2025-03-12 with different content.',
    },
  },
];

export function sourceByName(name: string): SourceDoc | undefined {
  return SOURCES.find((s) => s.name === name);
}
